# Generated by Django 3.2.9 on 2021-11-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20211112_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='pinterest_posters'),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster',
            field=models.ImageField(null=True, upload_to='pinterest_posters'),
        ),
    ]
